// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteSearch(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteSearch'](arg1, arg2, arg3);
}

export function ExportResultsJSON() {
  return window['go']['main']['App']['ExportResultsJSON']();
}

export function ExportResultsTXT() {
  return window['go']['main']['App']['ExportResultsTXT']();
}

export function GetAPIKey() {
  return window['go']['main']['App']['GetAPIKey']();
}

export function GetAllDorks() {
  return window['go']['main']['App']['GetAllDorks']();
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetCategoryCounts() {
  return window['go']['main']['App']['GetCategoryCounts']();
}

export function GetDorksByCategory(arg1) {
  return window['go']['main']['App']['GetDorksByCategory'](arg1);
}

export function GetFavorites() {
  return window['go']['main']['App']['GetFavorites']();
}

export function GetSearchMode(arg1, arg2) {
  return window['go']['main']['App']['GetSearchMode'](arg1, arg2);
}

export function HasAPIKey() {
  return window['go']['main']['App']['HasAPIKey']();
}

export function IsFavorite(arg1) {
  return window['go']['main']['App']['IsFavorite'](arg1);
}

export function IsMockMode() {
  return window['go']['main']['App']['IsMockMode']();
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}
