// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {dorks} from '../models';

export function ExecuteSearch(arg1:string,arg2:string,arg3:Array<string>):Promise<main.SearchResponse>;

export function ExportResultsJSON():Promise<void>;

export function ExportResultsTXT():Promise<void>;

export function GetAPIKey():Promise<string>;

export function GetAllDorks():Promise<Array<dorks.Dork>>;

export function GetCategories():Promise<Array<string>>;

export function GetCategoryCounts():Promise<Record<string, number>>;

export function GetDorksByCategory(arg1:string):Promise<Array<dorks.Dork>>;

export function GetFavorites():Promise<Array<string>>;

export function GetSearchMode(arg1:string,arg2:string):Promise<string>;

export function HasAPIKey():Promise<boolean>;

export function IsFavorite(arg1:string):Promise<boolean>;

export function IsMockMode():Promise<boolean>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function SetAPIKey(arg1:string):Promise<void>;

export function ToggleFavorite(arg1:string):Promise<boolean>;
